services:
  membersv-db:
    image: postgres:16
    environment:
      POSTGRES_DB: member_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - membersvdb_vol:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  membersvdb_vol: {}      